SELECT 
	SUM(CASE 
		WHEN P.CURRENCY = 111 THEN 
			P.AMOUNT
		ELSE 
			P.AMOUNT * R.EXCHANGE_RATE_TO_EUR
	END)
		AS "SUM(AMOUNT_EUR)",
		P.TRANSACTION_DATE

FROM 
	dbo.PAYMENTS as P
JOIN 
	dbo.CURRENCIES as C on C.CURRENCY_ID = P.CURRENCY
LEFT JOIN 
	dbo.BLACKLIST as B on B.USER_ID = P.USER_ID_SENDER
LEFT JOIN 
	dbo.CURRENCY_RATES as R on (R.CURRENCY_ID = P.CURRENCY AND R.EXCHANGE_DATE = P.TRANSACTION_DATE)
WHERE 
	B.USER_ID IS NULL
	AND C.END_DATE IS NULL
GROUP BY
	P.TRANSACTION_DATE